apps/inv/urls.py
from django.urls import path
#De esta App importamos las vistas
from .views import class_Categoria_View, class_Categoria_New_Form
from .views import class_Categoria_Update_Form, class_Categoria_Delete_Form

urlpatterns = [
    path('categorias/', class_Categoria_View.as_view(), name='html_categoria_list'),
    path('categorias/new', class_Categoria_New_Form.as_view(), name='html_categoria_form'),
    path('categorias/update/<int:pk>', class_Categoria_Update_Form.as_view(), name='html_categoria_update'),
    path('categorias/delete/<int:pk>', class_Categoria_Delete_Form.as_view(), name='html_categoria_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include(('apps.bases.urls','bases'), namespace='bases')),   
    path('inv/', include(('apps.inv.urls','inv'), namespace='inv')),   
]

apps/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)   
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(null=True, blank=True)
    class Meta:
        abstract=True

apps/inv/models.py
from django.db import models
#Importamos la Clase de la App "Bases"
from apps.bases.models import ClaseModelo
# Create your models here.

#Hereda de ClaseModelo, y ya tiene todas las propiedades de ClaseModelo
class Categoria(ClaseModelo):
    #El id es serial, no nos ocupamos de este campo
    #Sólo usamos la descripción
    descripcion = models.CharField(
        max_length=100, 
        help_text="Ayuda => Descripción de la categoría",
        unique=True
        )    
    #Cuando hagamos referencia al modelo Categoria, Django va a poner un
    # valor hexadecimal por defecto, para transformarlo usamos STR de un campo
    #Todos lo metodos siempre reciebn algo, sino se usa self
    def __str__ (self):
        return '{}'.format(self.descripcion)        
    #Para que la descripcion esté en mayusculas

    #Con este método grabo los cambios. si no está este metodo no se graba en la BBDD
    def save(self):
        self.descripcion = self.descripcion.upper()
        #Para guardar este self.description llamo al metodo save de la clase padre
        #Invocamos al Padre con Super, ¿qué invocamos? => el metodo save
        super(Categoria, self).save()

    #Django añade una "s" a las tablas, para que nos ea así, desde Meta lo modificamos
    class Meta:
        #Cuando se refiera en plural
        verbose_name_plural = "Categorias"

apps/inv/forms.py
from django import forms
from .models import Categoria
from django.forms import ModelForm

class class_Categoria_Form(forms.ModelForm):
    #Especificamos los datos generales con los que vamos a trabajar
    class Meta:
        #Con qué modelo trabajamos?
        model = Categoria
        #¿Qué campos usaremos o necesitamos?, serán los campos que el usuaio puede cambiar
        fields = ['descripcion','estado']
        #Especificamos las etiquetas. Para Descripcion que ponga => "Descripción de la categoria"
        labels = {'descripcion':"Descripción de la categoria",'estado':"Estado de la categoría"}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #¿Qué campos se van a mostrar?. Recorremos los campos a mostrar
        for campos_a_recorrer in iter(self.fields):
            self.fields[campos_a_recorrer].widget.attrs.update({
                'class': 'form-control'
            })
           

apps/inv/views.py
from django.shortcuts import render
#Para que si un suario está logeado.
from django.contrib.auth.mixins import LoginRequiredMixin
#Importo las vistas genericas
from django.views import generic
#Bebe sacar los datos del modelo que necesitamos
from .models import Categoria
#El formulario creado lo importamos desde la vista
from .forms import class_Categoria_Form
#Importo reverse_lazy para decir a donde dirigir al hacer click
from django.urls import reverse_lazy

# Create your views here.
# La vista es lo que se ve en el formulario, una ver renderizado
#Creamos una clase con el mixin que tenemos y las vistas genericas de Django
class class_Categoria_View(LoginRequiredMixin, generic.ListView):
    #Esta vista debe tener unas catecteristicas a cumplir
    #Asignamos el modelo
    model = Categoria
    template_name = "inv/html_categoria_list.html"
    #Importante, el contexto es la variable que le va a pasar a la vista con
    # la informacion que va a renderizar a la plantilla. A la plantilla le dijimos
    # que se va a llamar obj, por defecto Djagno le llama object, pero nosotros cambiamos 
    # el nombre con context_object_name
    context_object_name = "obj"
    #Si no estamos logeados, que nos pida logearnos
    #Si no estasmos redireccionados nos vamos a bases:html_login
    login_url = "bases:html_login"

#Creamos la vista del formulario.
#Con CreateView django ya va a interpretar que lo que se escribe es un insert en la BBDD
class class_Categoria_New_Form(LoginRequiredMixin, generic.CreateView):
    #Esta vista debe tener unas catecteristicas a cumplir
    #Asignamos el modelo
    model = Categoria
    template_name = "inv/html_categoria_form.html"
    #Importante, el contexto es la variable que le va a pasar a la vista con
    # la informacion que va a renderizar a la plantilla. A la plantilla le dijimos
    # que se va a llamar obj, por defecto Dajgno le llama object, pero nosotros cambiamos 
    # el nombre con context_object_name
    context_object_name = "obj"
    #Preguntamos que formulario va a renderizar
    form_class = class_Categoria_Form
    #Al dar submit que vaya a una URL. Al createView exige que se le diga
    #  a donde tiene que ir al hacer click
    #Es la ruta a donde va una vez que se crea el registro. El createView exige que se redireccione
    success_url = reverse_lazy("inv:html_categoria_list")  
    #Si no estamos logeados, que nos pida logearnos y nos vamos a bases:html_login
    login_url = "bases:html_login"
    
    #Cuando creamos el modelo habia una propiedad "crear usuario" con una foreingkey (id), 
    # no podiamos crear dos id.
    #Vamos a sobreescribir la propiedad, el metodo form_valid de esta vista para poder tener
    #  acceso a la informacion que se esta procesando o lo que se envia desde le formulario
    #  de ahí podemos coger datos de usuario que lo está procesando y manejar los datos del usuario
    def form_valid(self, form):
        #Accedemos al formulario desde este metodo
        #uc = usuario crear
        #con self.request.user cogemos el id del usuario (logeado) que está creando el formulario
        #Lo guarda en el formulario. Cogemos el usuario que crea el registro que era el campo "uc"
        form.instance.uc = self.request.user
        #Debemos retornar si el formulario es valido. Lo ahremos sobre el Padre con super()
        #Le mandamos el formulario que hemos modificado
        return super().form_valid(form)

#La Vista, va a ser igual que la createview, pero UpdateView
#Con poner CreateView, Django va a actualizar el registro
class class_Categoria_Update_Form(LoginRequiredMixin, generic.UpdateView):
    #Esta vista debe tener unas caracteristicas a cumplir
    #Asignamos el modelo
    model = Categoria
    template_name = "inv/html_categoria_form.html"
    #Importante, el contexto es la variable que le va a pasar a la vista con
    # la informacion que va a renderizar a la plantilla. A la plantilla le dijimos
    # que se va a llamar obj, por defecto Dajgno le llama object, pero nosotros cambiamos 
    # el nombre con context_object_name
    context_object_name = "obj"
    #Preguntamos que formulario va a renderizar
    form_class = class_Categoria_Form
    #Al dar submit que vaya a una URL. Al createView exige que se le diga
    #  a donde tiene que ir al hacer click
    #Es la ruta a donde va una vez que se crea el registro. El createView exige que se redireccione
    success_url = reverse_lazy("inv:html_categoria_list")  
    #Si no estamos logeados, que nos pida logearnos y nos vamos a bases:html_login
    login_url = "bases:html_login"
    
    #Cuando creamos el modelo habia una propiedad "crear usuario" con una foreingkey (id), no podiamos crear dos id
    #Vamos a sbreescribir la propiedad, el metodo form_valid de etsa vista para poder tener
    #  acceso a la informacion que se esta procesando o lo que se envia desde le formulario
    #  de ahí podemos coger datos de usuario que lo está procesando y manajar los datos del usuario
    def form_valid(self, form):
        #Accedemos al formulario desde este metodo                
        #Lo guarda en el formulario. Cogemos el campo "um", que es el usuario que modifica el registro
        #Coloco el user.id porque no lo puedo referencia con el foreignkey (este era para el uc), 
        #  En este caso um es un intgeger => um = models.IntegerField(null=True, blank=True)
        form.instance.um = self.request.user.id
        #Debemos retornar si el formulario es valido. Lo ahremos sobre el Padre con super()
        #Le mandamos el formulario que hemos modificado
        return super().form_valid(form)


class class_Categoria_Delete_Form(LoginRequiredMixin, generic.DeleteView):
    model = Categoria
    template_name = "inv/html_categoria_delete_form.html"
    context_object_name = "obj"
    success_url = reverse_lazy("inv:html_categoria_list")  
    login_url = "bases:html_login"
    

apps/inv/templates/inv/html_categoria_delete_form.html
<!-- Hereda de esta plantilla html_base.html-->
{% extends 'base/html_base.html' %}

{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<!-- Creamos el formulario -->
<form method="POST" class="form-inline">
    {% csrf_token %}

       <!-- Pending Requests Card Example -->
       <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {{obj.descripcion}}?</div>
                    <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i>Si Eliminar</button>
                    <a href="{% url 'inv:html_categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                
              </div>
              <div class="col-auto">
                <!-- <i class="fas fa-comments fa-2x text-gray-300"></i> -->
                <i class="fas fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    


</form>
{% endblock %}

<!-- Pegamos JS en esta parte. Lo sacamos de la documentacion de Jquery -->   
{% block js_page %}

{% endblock %}

apps/inv/templates/inv/html_categoria_form.html
<!-- Hereda de esta plantilla html_base.html-->
{% extends 'base/html_base.html' %}

{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<!-- Creamos el formulario -->
<form method="POST" class="form-inline">
    {% csrf_token %}
    <!-- <div class="col-xl-3 col-md-6 mb-4"> 
    Amplio el tamaño: -->
    <div class="col-xl-6 col-md-6 mb-6">
        <!-- Para preguntar por el color. Si objeto que viene o hay datos-->
        {% if obj %}
            <!-- Le ponemos un color distinto, en este caso rojo -->
            <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
            <!-- Colocamos otro color en este caso "success" -->
            <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        <!-- Preguntamos lo mismo que antes. Si hay un valor: Editar-->
                        {% if obj %}
                             Editar 
                        {% else %}                        
                             Nueva 
                        {% endif %}
                        Categoría
                    </div>
                    <!-- Colocamos esta linea. Es de la plantilla original 
                    Para que haga una dividion del titulo -->
                    <div class="dropdown-divider"></div>
                    <!-- Lo quito:
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div> -->
                    <!-- Aquí ya coloco los campos del formulario. De dos formas:
                        1. Manualmente
                        2. Con el formulario de Django -->
                        <!-- {{ form.as_p }} --> 
                    
                        <!-- 1. Manualmente  -->                    
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <!-- Escribimos dos div. En el tamaño de 10 va la descripcion -->
                        <div class="col-10">
                            <div class="input-group">
                                <!-- Importante que el name sea el del "modelo (model) y el id es igual que como hicimos en el login" -->
                                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"                                                                    
                                    value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                                <!-- Si vamos a editar un formulario debemos de usar la opcion value. 
                                 Si hay objeto, imprimo la variable, sino hno hace nada, no pongo else -->
                            </div>
                        </div>
                        <!-- Escribimos dos div. En el tamaño de 2 va el estado -->
                        <div class="col-2">
                            <div class="form-group">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                    {% if obj.estado %} 
                                        checked 
                                    {% endif %} >
                                   <!-- con el cjeckbox hacemos lo mismo --> 
                            </div>
                        </div>                     
                        <!-- 2. Si no se hace de forma manual  -->
                        <!-- {{ form.as_p }} -->
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <!-- Aqui estan lo botones, es decir un boton submit de color rojo -->
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <!-- Boton de cancelar, y con un vinculo para que si cancelamos se regresa a la lista de la categoria -->
                            <a href="{% url 'inv:html_categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

<!-- Pegamos JS en esta parte. Lo sacamos de la documentacion de Jquery -->   
{% block js_page %}

{% endblock %}

apps/inv/templates/inv/html_categoria_list.html
<!-- Hereda de la plantilla base con extends-->
{% extends 'base/html_base.html' %}
{% block page_content %}
<!-- Contenido -->
<!-- <div class="col-xl-8 col-lg-8"> -->
<div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías Principal</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Listado de Categorías:</div>
              <!-- Coloco el calendario en el item dropdown -->
              <!-- la url inv:html_categoria_form viene del 
                    name = html_categoria_form que esta en el fichero urls.py -->
              <a class="dropdown-item" href="{% url 'inv:html_categoria_form' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
              <a class="dropdown-item" href="#">Otra Accion_1</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Otra Accion_2</a>
          </div>           
        </div>
      </div>
    
      <!-- Card Body -->
      <div class="card-body">
        <!-- Sino hay categorias he de dar un mensaje.
        Preguntamos si está la variable Pontex con un If con el objeto: obj -->
            {% if not obj %}
              <!-- Podemos crear una alert de bootstrap, para ello
                    buscamos en Internet el codigo Bootstrap -->
                <div class="alert alert-danger" role="alert">
                  No hay categorias
                </div>                  
            {% else %}
            <!-- Si hay registros, pintamos una tabla -->
            <table class="table table-striped table-hover" id="datatable">
                <thread>
                    <!-- Los encabezados -->
                    <th>Id</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Fecha Creado</th>
                    <th>Fecha Modificado</th>
                    <!-- Quiero que esa columna se muetre siempre. Uso la Clase "All" -->
                    <th class="all">Acciones</th>
                    <!-- Hay un cuerpo -->
                  </thread>
                  <tbody>
                      {% for item in obj %}
                      <!-- Filas de objetos -->
                      <tr>
                          <td>{{ item.id }}</td>
                          <td>{{ item.descripcion}}</td>                        
                          <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                          <!---- Si quiero un filtro -->
                          <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                          <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                          <td>                          
                            <a href="{% url 'inv:html_categoria_update' item.id %}" class="btn btn-warning btn btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:html_categoria_delete' item.id %}" class="btn btn-danger btn btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                          </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                {% endif %}
            <!-- <div class="chart-area">
              <canvas id="myAreaChart"></canvas>
            </div> -->
      </div>
</div>
{% endblock %}

<!-- Vamos a poner un DataTable y he de poner esto 
   para que en cada pagina inicialice con un DataTable -->

<!-- Pegamos JS en esta parte. Lo sacamos de la documentacion de Jquery -->   
{% block js_page %}
<script>
  $(document).ready(function () {
    $('.table table-striped table-hover').DataTable();
  });
</script>
{% endblock %}